language: node_js

node_js:
  - "8.9.1"

env:
  global:
    secure: mMOXu+T0elTgSA36UGhiAff6ge3OYwbRz10Bm9A+SnMHnZlpJN/cVzlVLpcewfJWljJQGoVb7oifwTH0yTYzbRZPDHfohswPdm/mXpFrZOwjvCKNZsDrGwU/yvRBhk+A4nr6kfYGLLl4BODWZurLOoqTCZX8vH77h+pK3QqGbYFIFFBZoP8yirc8MkKrvW9Wb1wi2AyNoWx8iiG9p1upgGoHEU7QmEUpMxgAbYclyJXY7SUdqrrJUjOycc031/I3AIF6QAnDbb4w4RJ2B4+zsAXJnFlFFSrWRtO6MqCQZMKEr74t3t6aizi9nqU3UZeaXCFqfU9IzuXNmnDdFN3l2pljosxet4tEAuxyHn6MbLKRSvmMHROg+Z88Zgmoyy/S23VhSc0RHiPA/aE8psSFKfQlj7VNm9dRPizS/nPoW0ekdLELTfqWqDtx6yZAT+mKNuzH+6IU2bLeIPdIRfKjN+5nxL1fQNzrkouTAQQ50DIK4Bhl2C+20Cn6Hu++Vtnefm0yxRz4a7k27n1Nwps98MWbvV4m+WR/Pzmq/7mtvXgD4hryOy8dx4AHmHEndvEP5ItT7r5UGwexo/0dVPBY9X/w+kieHetqh12lM8daBV1ev8TmHGtT+zixzgiBZkOq+LRbRnnVuaeC5XL1ChMDRZoM6FgCypfR+Sa7m+v9bQo=

before_install:
  - export TZ=Asia/Taipei

install:
  - npm install

script:
  # Unit testing
  - npm run test
  # Set Git config
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git config --global push.default simple
  - git clone --depth 1 --branch gh-pages https://$GH_TOKEN@github.com/Panepo/Poliwag build
  # Generate static pages
  - npm run travis
  - cd build
  - git add -A .
  - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
  - git commit -m "Travis CI auto deploy:$MESSAGE"
  - git push --quiet

