export const SWITCH_MODE = 'SWITCH_MODE'

export const MODIFY_SPEED_FACTOR = 'MODIFY_SPEED_FACTOR'
export const MODIFY_REPORT_FACTOR = 'MODIFY_REPORT_FACTOR'
export const MODIFY_SOURCE_FACTOR = 'MODIFY_SOURCE_FACTOR'
export const MODIFY_NOISE_FACTOR = 'MODIFY_NOISE_FACTOR'
export const MODIFY_LINEAR_FACTOR = 'MODIFY_LINEAR_FACTOR'
export const MODIFY_JITTER_FACTOR = 'MODIFY_JITTER_FACTOR'
